version: '3'

services:
  postgresql:
    container_name: ckb-analyzer-postgresql
    image: timescale/timescaledb:latest-pg12
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/var/lib/postgresql/data:/var/lib/postgresql/data"

#   # This short service is used to import database schema.
#   # Schema file locates at "../src/schema.sql"
#   postgresql-init-schema:
#     container_name: ckb-analyzer-postgresql-init-schema
#     image: timescale/timescaledb:latest-pg12
#     env_file: .env
#     volumes:
#       - "../src/schema.sql:/var/lib/postgresql/data/schema.sql"
#     entrypoint: [ "bash", "-c", "sleep 3 && psql postgres://ckb:ckb@postgresql:5432 -f /var/lib/postgresql/data/schema.sql" ]
#     restart: "no"
#     depends_on:
#       - postgresql

  grafana:
    container_name: ckb-analyzer-grafana
    image: grafana/grafana:latest
    env_file: .env
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/etc/grafana:/etc/grafana
      - ./grafana/var/lib/grafana:/var/lib/grafana
    depends_on:
      - postgresql
