network = "aggron"
ipinfo_io_token = "e322ddf327f26b"

topics = ['CanonicalChainState', 'Reorganization', 'TxTransition', 'NetworkPropagation']

postgres = "postgres://<username>:<password>@<host>:<port>/ckb"

[node]
host = "127.0.0.1"
rpc_port = 8111
subscription_port = 18114
data_dir = "/home/ckb/nodes/node-8111/default/"
bootnodes = [
  # Hangzhou (China)
  "/ip4/47.111.169.36/tcp/8111/p2p/QmNQ4jky6uVqLDrPU7snqxARuNGWNLgSrTnssbRuy3ij2W",
  # Ohio (USA)
  "/ip4/18.217.146.65/tcp/8111/p2p/QmT6DFfm18wtbJz3y4aPNn3ac86N4d4p4xtfQRRPf73frC",
  # Singapore
  "/ip4/18.136.60.221/tcp/8111/p2p/QmTt6HeNakL8Fpmevrhdna7J4NzEMf9pLchf1CXtmtSrwb",
  # London
  "/ip4/35.176.207.239/tcp/8111/p2p/QmSJTsMsMGBjzv1oBNwQU36VhQRxc2WQpFoRu1ZifYKrjZ",
]
