[chain]
## default is false
# enabled = false
ckb_url = "http://127.0.0.1:8124"

[network]
## default is false
enabled = true
ckb_network_name = "lina" # "lina" | "aggron"
ckb_network_identifier = "/ckb/92b197aa" # mainnet

[topology]
## default is false
# enabled = false
ckb_urls = []

[influxdb]
database = "ckb"
url = "http://127.0.0.1:8086"
