on:
  push:
    tags:
      - 'v*'

name: Create Release

env:
  RELEASE_BIN: ckb-analyzer

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-18.04
            rust: 1.46.0
    steps:
    - uses: actions/checkout@v1

    - name: Cargo Build
      run: cargo build --verbose --release

    - name: Create Artifact Directory
      run: mkdir artifacts

    - name: Archive Release
      run: 7z a -ttar -so -an ./target/release/${{ env.RELEASE_BIN }} | 7z a -si ./artifacts/${{ env.RELEASE_BIN }}-linux-x86_64.tar.gz
      if: matrix.os == 'ubuntu-18.04'

    - name: Upload Relase
      uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}
        path: artifacts/
