on:
  push:
    tags:
      - 'v*'

name: Create Release

env:
  RELEASE_BIN: ckb-analyzer

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-18.04
            rust: 1.46.0
    steps:
    - uses: actions/checkout@v1

    - name: Cargo Build
      run: cargo build --verbose --release

    - name: Upload Relase
      uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}
        path: ${{ RELEASE_BIN }}
